export const USER_STATE_CHANGE = 'USER_STATE_CHANGE'
export const USER_EVENTS_STATE_CHANGE = 'USER_EVENTS_STATE_CHANGE'
export const USER_PHOTOS_STATE_CHANGE = 'USER_PHOTOS_STATE_CHANGE'
export const USER_FOLLOWING_STATE_CHANGE = 'USER_FOLLOWING_STATE_CHANGE'

export const USERS_EVENTS_STATE_CHANGE = 'USERS_EVENTS_STATE_CHANGE'
export const USERS_PHOTOS_STATE_CHANGE = 'USERS_PHOTOS_STATE_CHANGE'
export const USERS_DATA_STATE_CHANGE = 'USERS_DATA_STATE_CHANGE'
export const CLEAR_DATA = 'CLEAR_DATA'